[wifi:ap_scan]
KV_MODE = json
NO_BINARY_CHECK = true
category = Custom
pulldown_type = true
TIME_FORMAT = %s
TIME_PREFIX = "time":

[wifi:channel_survey]
KV_MODE = json
NO_BINARY_CHECK = true
category = Custom
pulldown_type = true
TIME_FORMAT = %s
TIME_PREFIX = "time":
